; individual declarations
(declare-const America World)
(declare-const England World)
(declare-const France World)
(declare-const Germany World)
(declare-const Italy World)

; class declarations
(declare-fun Pizza (World) Bool)
(declare-fun PizzaBase (World) Bool)
(declare-fun Food (World) Bool)
(declare-fun Spiciness (World) Bool)
(declare-fun PizzaTopping (World) Bool)
(declare-fun American (World) Bool)
(declare-fun NamedPizza (World) Bool)
(declare-fun MozzarellaTopping (World) Bool)
(declare-fun PeperoniSausageTopping (World) Bool)
(declare-fun TomatoTopping (World) Bool)
(declare-fun AmericanHot (World) Bool)
(declare-fun HotGreenPepperTopping (World) Bool)
(declare-fun JalapenoPepperTopping (World) Bool)
(declare-fun AnchoviesTopping (World) Bool)
(declare-fun FishTopping (World) Bool)
(declare-fun ArtichokeTopping (World) Bool)
(declare-fun VegetableTopping (World) Bool)
(declare-fun Mild (World) Bool)
(declare-fun AsparagusTopping (World) Bool)
(declare-fun Cajun (World) Bool)
(declare-fun OnionTopping (World) Bool)
(declare-fun PeperonataTopping (World) Bool)
(declare-fun PrawnsTopping (World) Bool)
(declare-fun TobascoPepperSauce (World) Bool)
(declare-fun CajunSpiceTopping (World) Bool)
(declare-fun HerbSpiceTopping (World) Bool)
(declare-fun Hot (World) Bool)
(declare-fun RosemaryTopping (World) Bool)
(declare-fun CaperTopping (World) Bool)
(declare-fun Capricciosa (World) Bool)
(declare-fun HamTopping (World) Bool)
(declare-fun OliveTopping (World) Bool)
(declare-fun Caprina (World) Bool)
(declare-fun GoatsCheeseTopping (World) Bool)
(declare-fun SundriedTomatoTopping (World) Bool)
(declare-fun CheeseTopping (World) Bool)
(declare-fun CheeseyPizza (World) Bool)
(declare-fun CheeseyVegetableTopping (World) Bool)
(declare-fun ChickenTopping (World) Bool)
(declare-fun MeatTopping (World) Bool)
(declare-fun Country (World) Bool)
(declare-fun DomainConcept (World) Bool)
(declare-fun DeepPanBase (World) Bool)
(declare-fun ThinAndCrispyBase (World) Bool)
(declare-fun ValuePartition (World) Bool)
(declare-fun Fiorentina (World) Bool)
(declare-fun GarlicTopping (World) Bool)
(declare-fun ParmesanTopping (World) Bool)
(declare-fun SpinachTopping (World) Bool)
(declare-fun FourCheesesTopping (World) Bool)
(declare-fun FourSeasons (World) Bool)
(declare-fun MushroomTopping (World) Bool)
(declare-fun FruitTopping (World) Bool)
(declare-fun FruttiDiMare (World) Bool)
(declare-fun MixedSeafoodTopping (World) Bool)
(declare-fun Medium (World) Bool)
(declare-fun Giardiniera (World) Bool)
(declare-fun LeekTopping (World) Bool)
(declare-fun PetitPoisTopping (World) Bool)
(declare-fun SlicedTomatoTopping (World) Bool)
(declare-fun GorgonzolaTopping (World) Bool)
(declare-fun GreenPepperTopping (World) Bool)
(declare-fun PepperTopping (World) Bool)
(declare-fun HotSpicedBeefTopping (World) Bool)
(declare-fun IceCream (World) Bool)
(declare-fun InterestingPizza (World) Bool)
(declare-fun LaReine (World) Bool)
(declare-fun Margherita (World) Bool)
(declare-fun MeatyPizza (World) Bool)
(declare-fun Mushroom (World) Bool)
(declare-fun Napoletana (World) Bool)
(declare-fun NonVegetarianPizza (World) Bool)
(declare-fun VegetarianPizza (World) Bool)
(declare-fun NutTopping (World) Bool)
(declare-fun ParmaHamTopping (World) Bool)
(declare-fun Parmense (World) Bool)
(declare-fun PineKernels (World) Bool)
(declare-fun PolloAdAstra (World) Bool)
(declare-fun RedOnionTopping (World) Bool)
(declare-fun SweetPepperTopping (World) Bool)
(declare-fun PrinceCarlo (World) Bool)
(declare-fun QuattroFormaggi (World) Bool)
(declare-fun RealItalianPizza (World) Bool)
(declare-fun RocketTopping (World) Bool)
(declare-fun Rosa (World) Bool)
(declare-fun SauceTopping (World) Bool)
(declare-fun Siciliana (World) Bool)
(declare-fun SloppyGiuseppe (World) Bool)
(declare-fun Soho (World) Bool)
(declare-fun SpicyPizza (World) Bool)
(declare-fun SpicyTopping (World) Bool)
(declare-fun SpicyPizzaEquivalent (World) Bool)
(declare-fun SultanaTopping (World) Bool)
(declare-fun ThinAndCrispyPizza (World) Bool)
(declare-fun UnclosedPizza (World) Bool)
(declare-fun VegetarianPizzaEquivalent1 (World) Bool)
(declare-fun VegetarianTopping (World) Bool)
(declare-fun VegetarianPizzaEquivalent2 (World) Bool)
(declare-fun Veneziana (World) Bool)

; property declarations
(declare-const hasBase Relation)
(declare-const hasIngredient Relation)
(declare-const isBaseOf Relation)
(declare-const hasCountryOfOrigin Relation)
(declare-const isIngredientOf Relation)
(declare-const hasSpiciness Relation)
(declare-const hasTopping Relation)
(declare-const isToppingOf Relation)
(declare-const title Relation)
(declare-const contributor Relation)
(declare-const license Relation)
(declare-const provenance Relation)
(declare-const description Relation)
(declare-const altLabel Relation)
(declare-const definition Relation)
(declare-const prefLabel Relation)

; different individuals
(assert (distinct America England France Germany Italy))

; class instances
(assert (Country America))
(assert (Country England))
(assert (Country France))
(assert (Country Germany))
(assert (Country Italy))

; disjoint classes
(assert (global (IceCream world) (not (Pizza world))))
(assert (global (IceCream world) (not (PizzaBase world))))
(assert (global (IceCream world) (not (PizzaTopping world))))
(assert (global (Pizza world) (not (IceCream world))))
(assert (global (Pizza world) (not (PizzaBase world))))
(assert (global (Pizza world) (not (PizzaTopping world))))
(assert (global (PizzaBase world) (not (IceCream world))))
(assert (global (PizzaBase world) (not (Pizza world))))
(assert (global (PizzaBase world) (not (PizzaTopping world))))
(assert (global (PizzaTopping world) (not (IceCream world))))
(assert (global (PizzaTopping world) (not (Pizza world))))
(assert (global (PizzaTopping world) (not (PizzaBase world))))
(assert (global (Hot world) (not (Medium world))))
(assert (global (Hot world) (not (Mild world))))
(assert (global (Medium world) (not (Hot world))))
(assert (global (Medium world) (not (Mild world))))
(assert (global (Mild world) (not (Hot world))))
(assert (global (Mild world) (not (Medium world))))
(assert (global (GreenPepperTopping world) (not (JalapenoPepperTopping world))))
(assert (global (GreenPepperTopping world) (not (PeperonataTopping world))))
(assert (global (GreenPepperTopping world) (not (SweetPepperTopping world))))
(assert (global (JalapenoPepperTopping world) (not (GreenPepperTopping world))))
(assert (global (JalapenoPepperTopping world) (not (PeperonataTopping world))))
(assert (global (JalapenoPepperTopping world) (not (SweetPepperTopping world))))
(assert (global (PeperonataTopping world) (not (GreenPepperTopping world))))
(assert (global (PeperonataTopping world) (not (JalapenoPepperTopping world))))
(assert (global (PeperonataTopping world) (not (SweetPepperTopping world))))
(assert (global (SweetPepperTopping world) (not (GreenPepperTopping world))))
(assert (global (SweetPepperTopping world) (not (JalapenoPepperTopping world))))
(assert (global (SweetPepperTopping world) (not (PeperonataTopping world))))
(assert (global (FourCheesesTopping world) (not (GoatsCheeseTopping world))))
(assert (global (FourCheesesTopping world) (not (GorgonzolaTopping world))))
(assert (global (FourCheesesTopping world) (not (MozzarellaTopping world))))
(assert (global (FourCheesesTopping world) (not (ParmesanTopping world))))
(assert (global (GoatsCheeseTopping world) (not (FourCheesesTopping world))))
(assert (global (GoatsCheeseTopping world) (not (GorgonzolaTopping world))))
(assert (global (GoatsCheeseTopping world) (not (MozzarellaTopping world))))
(assert (global (GoatsCheeseTopping world) (not (ParmesanTopping world))))
(assert (global (GorgonzolaTopping world) (not (FourCheesesTopping world))))
(assert (global (GorgonzolaTopping world) (not (GoatsCheeseTopping world))))
(assert (global (GorgonzolaTopping world) (not (MozzarellaTopping world))))
(assert (global (GorgonzolaTopping world) (not (ParmesanTopping world))))
(assert (global (MozzarellaTopping world) (not (FourCheesesTopping world))))
(assert (global (MozzarellaTopping world) (not (GoatsCheeseTopping world))))
(assert (global (MozzarellaTopping world) (not (GorgonzolaTopping world))))
(assert (global (MozzarellaTopping world) (not (ParmesanTopping world))))
(assert (global (ParmesanTopping world) (not (FourCheesesTopping world))))
(assert (global (ParmesanTopping world) (not (GoatsCheeseTopping world))))
(assert (global (ParmesanTopping world) (not (GorgonzolaTopping world))))
(assert (global (ParmesanTopping world) (not (MozzarellaTopping world))))
(assert (global (ChickenTopping world) (not (HamTopping world))))
(assert (global (ChickenTopping world) (not (HotSpicedBeefTopping world))))
(assert (global (ChickenTopping world) (not (PeperoniSausageTopping world))))
(assert (global (HamTopping world) (not (ChickenTopping world))))
(assert (global (HamTopping world) (not (HotSpicedBeefTopping world))))
(assert (global (HamTopping world) (not (PeperoniSausageTopping world))))
(assert (global (HotSpicedBeefTopping world) (not (ChickenTopping world))))
(assert (global (HotSpicedBeefTopping world) (not (HamTopping world))))
(assert (global (HotSpicedBeefTopping world) (not (PeperoniSausageTopping world))))
(assert (global (PeperoniSausageTopping world) (not (ChickenTopping world))))
(assert (global (PeperoniSausageTopping world) (not (HamTopping world))))
(assert (global (PeperoniSausageTopping world) (not (HotSpicedBeefTopping world))))
(assert (global (CheeseTopping world) (not (FishTopping world))))
(assert (global (CheeseTopping world) (not (FruitTopping world))))
(assert (global (CheeseTopping world) (not (HerbSpiceTopping world))))
(assert (global (CheeseTopping world) (not (MeatTopping world))))
(assert (global (CheeseTopping world) (not (NutTopping world))))
(assert (global (CheeseTopping world) (not (SauceTopping world))))
(assert (global (CheeseTopping world) (not (VegetableTopping world))))
(assert (global (FishTopping world) (not (CheeseTopping world))))
(assert (global (FishTopping world) (not (FruitTopping world))))
(assert (global (FishTopping world) (not (HerbSpiceTopping world))))
(assert (global (FishTopping world) (not (MeatTopping world))))
(assert (global (FishTopping world) (not (NutTopping world))))
(assert (global (FishTopping world) (not (SauceTopping world))))
(assert (global (FishTopping world) (not (VegetableTopping world))))
(assert (global (FruitTopping world) (not (CheeseTopping world))))
(assert (global (FruitTopping world) (not (FishTopping world))))
(assert (global (FruitTopping world) (not (HerbSpiceTopping world))))
(assert (global (FruitTopping world) (not (MeatTopping world))))
(assert (global (FruitTopping world) (not (NutTopping world))))
(assert (global (FruitTopping world) (not (SauceTopping world))))
(assert (global (FruitTopping world) (not (VegetableTopping world))))
(assert (global (HerbSpiceTopping world) (not (CheeseTopping world))))
(assert (global (HerbSpiceTopping world) (not (FishTopping world))))
(assert (global (HerbSpiceTopping world) (not (FruitTopping world))))
(assert (global (HerbSpiceTopping world) (not (MeatTopping world))))
(assert (global (HerbSpiceTopping world) (not (NutTopping world))))
(assert (global (HerbSpiceTopping world) (not (SauceTopping world))))
(assert (global (HerbSpiceTopping world) (not (VegetableTopping world))))
(assert (global (MeatTopping world) (not (CheeseTopping world))))
(assert (global (MeatTopping world) (not (FishTopping world))))
(assert (global (MeatTopping world) (not (FruitTopping world))))
(assert (global (MeatTopping world) (not (HerbSpiceTopping world))))
(assert (global (MeatTopping world) (not (NutTopping world))))
(assert (global (MeatTopping world) (not (SauceTopping world))))
(assert (global (MeatTopping world) (not (VegetableTopping world))))
(assert (global (NutTopping world) (not (CheeseTopping world))))
(assert (global (NutTopping world) (not (FishTopping world))))
(assert (global (NutTopping world) (not (FruitTopping world))))
(assert (global (NutTopping world) (not (HerbSpiceTopping world))))
(assert (global (NutTopping world) (not (MeatTopping world))))
(assert (global (NutTopping world) (not (SauceTopping world))))
(assert (global (NutTopping world) (not (VegetableTopping world))))
(assert (global (SauceTopping world) (not (CheeseTopping world))))
(assert (global (SauceTopping world) (not (FishTopping world))))
(assert (global (SauceTopping world) (not (FruitTopping world))))
(assert (global (SauceTopping world) (not (HerbSpiceTopping world))))
(assert (global (SauceTopping world) (not (MeatTopping world))))
(assert (global (SauceTopping world) (not (NutTopping world))))
(assert (global (SauceTopping world) (not (VegetableTopping world))))
(assert (global (VegetableTopping world) (not (CheeseTopping world))))
(assert (global (VegetableTopping world) (not (FishTopping world))))
(assert (global (VegetableTopping world) (not (FruitTopping world))))
(assert (global (VegetableTopping world) (not (HerbSpiceTopping world))))
(assert (global (VegetableTopping world) (not (MeatTopping world))))
(assert (global (VegetableTopping world) (not (NutTopping world))))
(assert (global (VegetableTopping world) (not (SauceTopping world))))
(assert (global (ArtichokeTopping world) (not (AsparagusTopping world))))
(assert (global (ArtichokeTopping world) (not (CaperTopping world))))
(assert (global (ArtichokeTopping world) (not (GarlicTopping world))))
(assert (global (ArtichokeTopping world) (not (LeekTopping world))))
(assert (global (ArtichokeTopping world) (not (MushroomTopping world))))
(assert (global (ArtichokeTopping world) (not (OliveTopping world))))
(assert (global (ArtichokeTopping world) (not (OnionTopping world))))
(assert (global (ArtichokeTopping world) (not (PepperTopping world))))
(assert (global (ArtichokeTopping world) (not (PetitPoisTopping world))))
(assert (global (ArtichokeTopping world) (not (RocketTopping world))))
(assert (global (ArtichokeTopping world) (not (SpinachTopping world))))
(assert (global (ArtichokeTopping world) (not (TomatoTopping world))))
(assert (global (AsparagusTopping world) (not (ArtichokeTopping world))))
(assert (global (AsparagusTopping world) (not (CaperTopping world))))
(assert (global (AsparagusTopping world) (not (GarlicTopping world))))
(assert (global (AsparagusTopping world) (not (LeekTopping world))))
(assert (global (AsparagusTopping world) (not (MushroomTopping world))))
(assert (global (AsparagusTopping world) (not (OliveTopping world))))
(assert (global (AsparagusTopping world) (not (OnionTopping world))))
(assert (global (AsparagusTopping world) (not (PepperTopping world))))
(assert (global (AsparagusTopping world) (not (PetitPoisTopping world))))
(assert (global (AsparagusTopping world) (not (RocketTopping world))))
(assert (global (AsparagusTopping world) (not (SpinachTopping world))))
(assert (global (AsparagusTopping world) (not (TomatoTopping world))))
(assert (global (CaperTopping world) (not (ArtichokeTopping world))))
(assert (global (CaperTopping world) (not (AsparagusTopping world))))
(assert (global (CaperTopping world) (not (GarlicTopping world))))
(assert (global (CaperTopping world) (not (LeekTopping world))))
(assert (global (CaperTopping world) (not (MushroomTopping world))))
(assert (global (CaperTopping world) (not (OliveTopping world))))
(assert (global (CaperTopping world) (not (OnionTopping world))))
(assert (global (CaperTopping world) (not (PepperTopping world))))
(assert (global (CaperTopping world) (not (PetitPoisTopping world))))
(assert (global (CaperTopping world) (not (RocketTopping world))))
(assert (global (CaperTopping world) (not (SpinachTopping world))))
(assert (global (CaperTopping world) (not (TomatoTopping world))))
(assert (global (GarlicTopping world) (not (ArtichokeTopping world))))
(assert (global (GarlicTopping world) (not (AsparagusTopping world))))
(assert (global (GarlicTopping world) (not (CaperTopping world))))
(assert (global (GarlicTopping world) (not (LeekTopping world))))
(assert (global (GarlicTopping world) (not (MushroomTopping world))))
(assert (global (GarlicTopping world) (not (OliveTopping world))))
(assert (global (GarlicTopping world) (not (OnionTopping world))))
(assert (global (GarlicTopping world) (not (PepperTopping world))))
(assert (global (GarlicTopping world) (not (PetitPoisTopping world))))
(assert (global (GarlicTopping world) (not (RocketTopping world))))
(assert (global (GarlicTopping world) (not (SpinachTopping world))))
(assert (global (GarlicTopping world) (not (TomatoTopping world))))
(assert (global (LeekTopping world) (not (ArtichokeTopping world))))
(assert (global (LeekTopping world) (not (AsparagusTopping world))))
(assert (global (LeekTopping world) (not (CaperTopping world))))
(assert (global (LeekTopping world) (not (GarlicTopping world))))
(assert (global (LeekTopping world) (not (MushroomTopping world))))
(assert (global (LeekTopping world) (not (OliveTopping world))))
(assert (global (LeekTopping world) (not (OnionTopping world))))
(assert (global (LeekTopping world) (not (PepperTopping world))))
(assert (global (LeekTopping world) (not (PetitPoisTopping world))))
(assert (global (LeekTopping world) (not (RocketTopping world))))
(assert (global (LeekTopping world) (not (SpinachTopping world))))
(assert (global (LeekTopping world) (not (TomatoTopping world))))
(assert (global (MushroomTopping world) (not (ArtichokeTopping world))))
(assert (global (MushroomTopping world) (not (AsparagusTopping world))))
(assert (global (MushroomTopping world) (not (CaperTopping world))))
(assert (global (MushroomTopping world) (not (GarlicTopping world))))
(assert (global (MushroomTopping world) (not (LeekTopping world))))
(assert (global (MushroomTopping world) (not (OliveTopping world))))
(assert (global (MushroomTopping world) (not (OnionTopping world))))
(assert (global (MushroomTopping world) (not (PepperTopping world))))
(assert (global (MushroomTopping world) (not (PetitPoisTopping world))))
(assert (global (MushroomTopping world) (not (RocketTopping world))))
(assert (global (MushroomTopping world) (not (SpinachTopping world))))
(assert (global (MushroomTopping world) (not (TomatoTopping world))))
(assert (global (OliveTopping world) (not (ArtichokeTopping world))))
(assert (global (OliveTopping world) (not (AsparagusTopping world))))
(assert (global (OliveTopping world) (not (CaperTopping world))))
(assert (global (OliveTopping world) (not (GarlicTopping world))))
(assert (global (OliveTopping world) (not (LeekTopping world))))
(assert (global (OliveTopping world) (not (MushroomTopping world))))
(assert (global (OliveTopping world) (not (OnionTopping world))))
(assert (global (OliveTopping world) (not (PepperTopping world))))
(assert (global (OliveTopping world) (not (PetitPoisTopping world))))
(assert (global (OliveTopping world) (not (RocketTopping world))))
(assert (global (OliveTopping world) (not (SpinachTopping world))))
(assert (global (OliveTopping world) (not (TomatoTopping world))))
(assert (global (OnionTopping world) (not (ArtichokeTopping world))))
(assert (global (OnionTopping world) (not (AsparagusTopping world))))
(assert (global (OnionTopping world) (not (CaperTopping world))))
(assert (global (OnionTopping world) (not (GarlicTopping world))))
(assert (global (OnionTopping world) (not (LeekTopping world))))
(assert (global (OnionTopping world) (not (MushroomTopping world))))
(assert (global (OnionTopping world) (not (OliveTopping world))))
(assert (global (OnionTopping world) (not (PepperTopping world))))
(assert (global (OnionTopping world) (not (PetitPoisTopping world))))
(assert (global (OnionTopping world) (not (RocketTopping world))))
(assert (global (OnionTopping world) (not (SpinachTopping world))))
(assert (global (OnionTopping world) (not (TomatoTopping world))))
(assert (global (PepperTopping world) (not (ArtichokeTopping world))))
(assert (global (PepperTopping world) (not (AsparagusTopping world))))
(assert (global (PepperTopping world) (not (CaperTopping world))))
(assert (global (PepperTopping world) (not (GarlicTopping world))))
(assert (global (PepperTopping world) (not (LeekTopping world))))
(assert (global (PepperTopping world) (not (MushroomTopping world))))
(assert (global (PepperTopping world) (not (OliveTopping world))))
(assert (global (PepperTopping world) (not (OnionTopping world))))
(assert (global (PepperTopping world) (not (PetitPoisTopping world))))
(assert (global (PepperTopping world) (not (RocketTopping world))))
(assert (global (PepperTopping world) (not (SpinachTopping world))))
(assert (global (PepperTopping world) (not (TomatoTopping world))))
(assert (global (PetitPoisTopping world) (not (ArtichokeTopping world))))
(assert (global (PetitPoisTopping world) (not (AsparagusTopping world))))
(assert (global (PetitPoisTopping world) (not (CaperTopping world))))
(assert (global (PetitPoisTopping world) (not (GarlicTopping world))))
(assert (global (PetitPoisTopping world) (not (LeekTopping world))))
(assert (global (PetitPoisTopping world) (not (MushroomTopping world))))
(assert (global (PetitPoisTopping world) (not (OliveTopping world))))
(assert (global (PetitPoisTopping world) (not (OnionTopping world))))
(assert (global (PetitPoisTopping world) (not (PepperTopping world))))
(assert (global (PetitPoisTopping world) (not (RocketTopping world))))
(assert (global (PetitPoisTopping world) (not (SpinachTopping world))))
(assert (global (PetitPoisTopping world) (not (TomatoTopping world))))
(assert (global (RocketTopping world) (not (ArtichokeTopping world))))
(assert (global (RocketTopping world) (not (AsparagusTopping world))))
(assert (global (RocketTopping world) (not (CaperTopping world))))
(assert (global (RocketTopping world) (not (GarlicTopping world))))
(assert (global (RocketTopping world) (not (LeekTopping world))))
(assert (global (RocketTopping world) (not (MushroomTopping world))))
(assert (global (RocketTopping world) (not (OliveTopping world))))
(assert (global (RocketTopping world) (not (OnionTopping world))))
(assert (global (RocketTopping world) (not (PepperTopping world))))
(assert (global (RocketTopping world) (not (PetitPoisTopping world))))
(assert (global (RocketTopping world) (not (SpinachTopping world))))
(assert (global (RocketTopping world) (not (TomatoTopping world))))
(assert (global (SpinachTopping world) (not (ArtichokeTopping world))))
(assert (global (SpinachTopping world) (not (AsparagusTopping world))))
(assert (global (SpinachTopping world) (not (CaperTopping world))))
(assert (global (SpinachTopping world) (not (GarlicTopping world))))
(assert (global (SpinachTopping world) (not (LeekTopping world))))
(assert (global (SpinachTopping world) (not (MushroomTopping world))))
(assert (global (SpinachTopping world) (not (OliveTopping world))))
(assert (global (SpinachTopping world) (not (OnionTopping world))))
(assert (global (SpinachTopping world) (not (PepperTopping world))))
(assert (global (SpinachTopping world) (not (PetitPoisTopping world))))
(assert (global (SpinachTopping world) (not (RocketTopping world))))
(assert (global (SpinachTopping world) (not (TomatoTopping world))))
(assert (global (TomatoTopping world) (not (ArtichokeTopping world))))
(assert (global (TomatoTopping world) (not (AsparagusTopping world))))
(assert (global (TomatoTopping world) (not (CaperTopping world))))
(assert (global (TomatoTopping world) (not (GarlicTopping world))))
(assert (global (TomatoTopping world) (not (LeekTopping world))))
(assert (global (TomatoTopping world) (not (MushroomTopping world))))
(assert (global (TomatoTopping world) (not (OliveTopping world))))
(assert (global (TomatoTopping world) (not (OnionTopping world))))
(assert (global (TomatoTopping world) (not (PepperTopping world))))
(assert (global (TomatoTopping world) (not (PetitPoisTopping world))))
(assert (global (TomatoTopping world) (not (RocketTopping world))))
(assert (global (TomatoTopping world) (not (SpinachTopping world))))
(assert (global (AnchoviesTopping world) (not (MixedSeafoodTopping world))))
(assert (global (AnchoviesTopping world) (not (PrawnsTopping world))))
(assert (global (MixedSeafoodTopping world) (not (AnchoviesTopping world))))
(assert (global (MixedSeafoodTopping world) (not (PrawnsTopping world))))
(assert (global (PrawnsTopping world) (not (AnchoviesTopping world))))
(assert (global (PrawnsTopping world) (not (MixedSeafoodTopping world))))
(assert (global (American world) (not (AmericanHot world))))
(assert (global (American world) (not (Cajun world))))
(assert (global (American world) (not (Capricciosa world))))
(assert (global (American world) (not (Caprina world))))
(assert (global (American world) (not (Fiorentina world))))
(assert (global (American world) (not (FourSeasons world))))
(assert (global (American world) (not (FruttiDiMare world))))
(assert (global (American world) (not (Giardiniera world))))
(assert (global (American world) (not (LaReine world))))
(assert (global (American world) (not (Margherita world))))
(assert (global (American world) (not (Mushroom world))))
(assert (global (American world) (not (Napoletana world))))
(assert (global (American world) (not (Parmense world))))
(assert (global (American world) (not (PolloAdAstra world))))
(assert (global (American world) (not (PrinceCarlo world))))
(assert (global (American world) (not (QuattroFormaggi world))))
(assert (global (American world) (not (Rosa world))))
(assert (global (American world) (not (Siciliana world))))
(assert (global (American world) (not (SloppyGiuseppe world))))
(assert (global (American world) (not (Soho world))))
(assert (global (American world) (not (UnclosedPizza world))))
(assert (global (American world) (not (Veneziana world))))
(assert (global (AmericanHot world) (not (American world))))
(assert (global (AmericanHot world) (not (Cajun world))))
(assert (global (AmericanHot world) (not (Capricciosa world))))
(assert (global (AmericanHot world) (not (Caprina world))))
(assert (global (AmericanHot world) (not (Fiorentina world))))
(assert (global (AmericanHot world) (not (FourSeasons world))))
(assert (global (AmericanHot world) (not (FruttiDiMare world))))
(assert (global (AmericanHot world) (not (Giardiniera world))))
(assert (global (AmericanHot world) (not (LaReine world))))
(assert (global (AmericanHot world) (not (Margherita world))))
(assert (global (AmericanHot world) (not (Mushroom world))))
(assert (global (AmericanHot world) (not (Napoletana world))))
(assert (global (AmericanHot world) (not (Parmense world))))
(assert (global (AmericanHot world) (not (PolloAdAstra world))))
(assert (global (AmericanHot world) (not (PrinceCarlo world))))
(assert (global (AmericanHot world) (not (QuattroFormaggi world))))
(assert (global (AmericanHot world) (not (Rosa world))))
(assert (global (AmericanHot world) (not (Siciliana world))))
(assert (global (AmericanHot world) (not (SloppyGiuseppe world))))
(assert (global (AmericanHot world) (not (Soho world))))
(assert (global (AmericanHot world) (not (UnclosedPizza world))))
(assert (global (AmericanHot world) (not (Veneziana world))))
(assert (global (Cajun world) (not (American world))))
(assert (global (Cajun world) (not (AmericanHot world))))
(assert (global (Cajun world) (not (Capricciosa world))))
(assert (global (Cajun world) (not (Caprina world))))
(assert (global (Cajun world) (not (Fiorentina world))))
(assert (global (Cajun world) (not (FourSeasons world))))
(assert (global (Cajun world) (not (FruttiDiMare world))))
(assert (global (Cajun world) (not (Giardiniera world))))
(assert (global (Cajun world) (not (LaReine world))))
(assert (global (Cajun world) (not (Margherita world))))
(assert (global (Cajun world) (not (Mushroom world))))
(assert (global (Cajun world) (not (Napoletana world))))
(assert (global (Cajun world) (not (Parmense world))))
(assert (global (Cajun world) (not (PolloAdAstra world))))
(assert (global (Cajun world) (not (PrinceCarlo world))))
(assert (global (Cajun world) (not (QuattroFormaggi world))))
(assert (global (Cajun world) (not (Rosa world))))
(assert (global (Cajun world) (not (Siciliana world))))
(assert (global (Cajun world) (not (SloppyGiuseppe world))))
(assert (global (Cajun world) (not (Soho world))))
(assert (global (Cajun world) (not (UnclosedPizza world))))
(assert (global (Cajun world) (not (Veneziana world))))
(assert (global (Capricciosa world) (not (American world))))
(assert (global (Capricciosa world) (not (AmericanHot world))))
(assert (global (Capricciosa world) (not (Cajun world))))
(assert (global (Capricciosa world) (not (Caprina world))))
(assert (global (Capricciosa world) (not (Fiorentina world))))
(assert (global (Capricciosa world) (not (FourSeasons world))))
(assert (global (Capricciosa world) (not (FruttiDiMare world))))
(assert (global (Capricciosa world) (not (Giardiniera world))))
(assert (global (Capricciosa world) (not (LaReine world))))
(assert (global (Capricciosa world) (not (Margherita world))))
(assert (global (Capricciosa world) (not (Mushroom world))))
(assert (global (Capricciosa world) (not (Napoletana world))))
(assert (global (Capricciosa world) (not (Parmense world))))
(assert (global (Capricciosa world) (not (PolloAdAstra world))))
(assert (global (Capricciosa world) (not (PrinceCarlo world))))
(assert (global (Capricciosa world) (not (QuattroFormaggi world))))
(assert (global (Capricciosa world) (not (Rosa world))))
(assert (global (Capricciosa world) (not (Siciliana world))))
(assert (global (Capricciosa world) (not (SloppyGiuseppe world))))
(assert (global (Capricciosa world) (not (Soho world))))
(assert (global (Capricciosa world) (not (UnclosedPizza world))))
(assert (global (Capricciosa world) (not (Veneziana world))))
(assert (global (Caprina world) (not (American world))))
(assert (global (Caprina world) (not (AmericanHot world))))
(assert (global (Caprina world) (not (Cajun world))))
(assert (global (Caprina world) (not (Capricciosa world))))
(assert (global (Caprina world) (not (Fiorentina world))))
(assert (global (Caprina world) (not (FourSeasons world))))
(assert (global (Caprina world) (not (FruttiDiMare world))))
(assert (global (Caprina world) (not (Giardiniera world))))
(assert (global (Caprina world) (not (LaReine world))))
(assert (global (Caprina world) (not (Margherita world))))
(assert (global (Caprina world) (not (Mushroom world))))
(assert (global (Caprina world) (not (Napoletana world))))
(assert (global (Caprina world) (not (Parmense world))))
(assert (global (Caprina world) (not (PolloAdAstra world))))
(assert (global (Caprina world) (not (PrinceCarlo world))))
(assert (global (Caprina world) (not (QuattroFormaggi world))))
(assert (global (Caprina world) (not (Rosa world))))
(assert (global (Caprina world) (not (Siciliana world))))
(assert (global (Caprina world) (not (SloppyGiuseppe world))))
(assert (global (Caprina world) (not (Soho world))))
(assert (global (Caprina world) (not (UnclosedPizza world))))
(assert (global (Caprina world) (not (Veneziana world))))
(assert (global (Fiorentina world) (not (American world))))
(assert (global (Fiorentina world) (not (AmericanHot world))))
(assert (global (Fiorentina world) (not (Cajun world))))
(assert (global (Fiorentina world) (not (Capricciosa world))))
(assert (global (Fiorentina world) (not (Caprina world))))
(assert (global (Fiorentina world) (not (FourSeasons world))))
(assert (global (Fiorentina world) (not (FruttiDiMare world))))
(assert (global (Fiorentina world) (not (Giardiniera world))))
(assert (global (Fiorentina world) (not (LaReine world))))
(assert (global (Fiorentina world) (not (Margherita world))))
(assert (global (Fiorentina world) (not (Mushroom world))))
(assert (global (Fiorentina world) (not (Napoletana world))))
(assert (global (Fiorentina world) (not (Parmense world))))
(assert (global (Fiorentina world) (not (PolloAdAstra world))))
(assert (global (Fiorentina world) (not (PrinceCarlo world))))
(assert (global (Fiorentina world) (not (QuattroFormaggi world))))
(assert (global (Fiorentina world) (not (Rosa world))))
(assert (global (Fiorentina world) (not (Siciliana world))))
(assert (global (Fiorentina world) (not (SloppyGiuseppe world))))
(assert (global (Fiorentina world) (not (Soho world))))
(assert (global (Fiorentina world) (not (UnclosedPizza world))))
(assert (global (Fiorentina world) (not (Veneziana world))))
(assert (global (FourSeasons world) (not (American world))))
(assert (global (FourSeasons world) (not (AmericanHot world))))
(assert (global (FourSeasons world) (not (Cajun world))))
(assert (global (FourSeasons world) (not (Capricciosa world))))
(assert (global (FourSeasons world) (not (Caprina world))))
(assert (global (FourSeasons world) (not (Fiorentina world))))
(assert (global (FourSeasons world) (not (FruttiDiMare world))))
(assert (global (FourSeasons world) (not (Giardiniera world))))
(assert (global (FourSeasons world) (not (LaReine world))))
(assert (global (FourSeasons world) (not (Margherita world))))
(assert (global (FourSeasons world) (not (Mushroom world))))
(assert (global (FourSeasons world) (not (Napoletana world))))
(assert (global (FourSeasons world) (not (Parmense world))))
(assert (global (FourSeasons world) (not (PolloAdAstra world))))
(assert (global (FourSeasons world) (not (PrinceCarlo world))))
(assert (global (FourSeasons world) (not (QuattroFormaggi world))))
(assert (global (FourSeasons world) (not (Rosa world))))
(assert (global (FourSeasons world) (not (Siciliana world))))
(assert (global (FourSeasons world) (not (SloppyGiuseppe world))))
(assert (global (FourSeasons world) (not (Soho world))))
(assert (global (FourSeasons world) (not (UnclosedPizza world))))
(assert (global (FourSeasons world) (not (Veneziana world))))
(assert (global (FruttiDiMare world) (not (American world))))
(assert (global (FruttiDiMare world) (not (AmericanHot world))))
(assert (global (FruttiDiMare world) (not (Cajun world))))
(assert (global (FruttiDiMare world) (not (Capricciosa world))))
(assert (global (FruttiDiMare world) (not (Caprina world))))
(assert (global (FruttiDiMare world) (not (Fiorentina world))))
(assert (global (FruttiDiMare world) (not (FourSeasons world))))
(assert (global (FruttiDiMare world) (not (Giardiniera world))))
(assert (global (FruttiDiMare world) (not (LaReine world))))
(assert (global (FruttiDiMare world) (not (Margherita world))))
(assert (global (FruttiDiMare world) (not (Mushroom world))))
(assert (global (FruttiDiMare world) (not (Napoletana world))))
(assert (global (FruttiDiMare world) (not (Parmense world))))
(assert (global (FruttiDiMare world) (not (PolloAdAstra world))))
(assert (global (FruttiDiMare world) (not (PrinceCarlo world))))
(assert (global (FruttiDiMare world) (not (QuattroFormaggi world))))
(assert (global (FruttiDiMare world) (not (Rosa world))))
(assert (global (FruttiDiMare world) (not (Siciliana world))))
(assert (global (FruttiDiMare world) (not (SloppyGiuseppe world))))
(assert (global (FruttiDiMare world) (not (Soho world))))
(assert (global (FruttiDiMare world) (not (UnclosedPizza world))))
(assert (global (FruttiDiMare world) (not (Veneziana world))))
(assert (global (Giardiniera world) (not (American world))))
(assert (global (Giardiniera world) (not (AmericanHot world))))
(assert (global (Giardiniera world) (not (Cajun world))))
(assert (global (Giardiniera world) (not (Capricciosa world))))
(assert (global (Giardiniera world) (not (Caprina world))))
(assert (global (Giardiniera world) (not (Fiorentina world))))
(assert (global (Giardiniera world) (not (FourSeasons world))))
(assert (global (Giardiniera world) (not (FruttiDiMare world))))
(assert (global (Giardiniera world) (not (LaReine world))))
(assert (global (Giardiniera world) (not (Margherita world))))
(assert (global (Giardiniera world) (not (Mushroom world))))
(assert (global (Giardiniera world) (not (Napoletana world))))
(assert (global (Giardiniera world) (not (Parmense world))))
(assert (global (Giardiniera world) (not (PolloAdAstra world))))
(assert (global (Giardiniera world) (not (PrinceCarlo world))))
(assert (global (Giardiniera world) (not (QuattroFormaggi world))))
(assert (global (Giardiniera world) (not (Rosa world))))
(assert (global (Giardiniera world) (not (Siciliana world))))
(assert (global (Giardiniera world) (not (SloppyGiuseppe world))))
(assert (global (Giardiniera world) (not (Soho world))))
(assert (global (Giardiniera world) (not (UnclosedPizza world))))
(assert (global (Giardiniera world) (not (Veneziana world))))
(assert (global (LaReine world) (not (American world))))
(assert (global (LaReine world) (not (AmericanHot world))))
(assert (global (LaReine world) (not (Cajun world))))
(assert (global (LaReine world) (not (Capricciosa world))))
(assert (global (LaReine world) (not (Caprina world))))
(assert (global (LaReine world) (not (Fiorentina world))))
(assert (global (LaReine world) (not (FourSeasons world))))
(assert (global (LaReine world) (not (FruttiDiMare world))))
(assert (global (LaReine world) (not (Giardiniera world))))
(assert (global (LaReine world) (not (Margherita world))))
(assert (global (LaReine world) (not (Mushroom world))))
(assert (global (LaReine world) (not (Napoletana world))))
(assert (global (LaReine world) (not (Parmense world))))
(assert (global (LaReine world) (not (PolloAdAstra world))))
(assert (global (LaReine world) (not (PrinceCarlo world))))
(assert (global (LaReine world) (not (QuattroFormaggi world))))
(assert (global (LaReine world) (not (Rosa world))))
(assert (global (LaReine world) (not (Siciliana world))))
(assert (global (LaReine world) (not (SloppyGiuseppe world))))
(assert (global (LaReine world) (not (Soho world))))
(assert (global (LaReine world) (not (UnclosedPizza world))))
(assert (global (LaReine world) (not (Veneziana world))))
(assert (global (Margherita world) (not (American world))))
(assert (global (Margherita world) (not (AmericanHot world))))
(assert (global (Margherita world) (not (Cajun world))))
(assert (global (Margherita world) (not (Capricciosa world))))
(assert (global (Margherita world) (not (Caprina world))))
(assert (global (Margherita world) (not (Fiorentina world))))
(assert (global (Margherita world) (not (FourSeasons world))))
(assert (global (Margherita world) (not (FruttiDiMare world))))
(assert (global (Margherita world) (not (Giardiniera world))))
(assert (global (Margherita world) (not (LaReine world))))
(assert (global (Margherita world) (not (Mushroom world))))
(assert (global (Margherita world) (not (Napoletana world))))
(assert (global (Margherita world) (not (Parmense world))))
(assert (global (Margherita world) (not (PolloAdAstra world))))
(assert (global (Margherita world) (not (PrinceCarlo world))))
(assert (global (Margherita world) (not (QuattroFormaggi world))))
(assert (global (Margherita world) (not (Rosa world))))
(assert (global (Margherita world) (not (Siciliana world))))
(assert (global (Margherita world) (not (SloppyGiuseppe world))))
(assert (global (Margherita world) (not (Soho world))))
(assert (global (Margherita world) (not (UnclosedPizza world))))
(assert (global (Margherita world) (not (Veneziana world))))
(assert (global (Mushroom world) (not (American world))))
(assert (global (Mushroom world) (not (AmericanHot world))))
(assert (global (Mushroom world) (not (Cajun world))))
(assert (global (Mushroom world) (not (Capricciosa world))))
(assert (global (Mushroom world) (not (Caprina world))))
(assert (global (Mushroom world) (not (Fiorentina world))))
(assert (global (Mushroom world) (not (FourSeasons world))))
(assert (global (Mushroom world) (not (FruttiDiMare world))))
(assert (global (Mushroom world) (not (Giardiniera world))))
(assert (global (Mushroom world) (not (LaReine world))))
(assert (global (Mushroom world) (not (Margherita world))))
(assert (global (Mushroom world) (not (Napoletana world))))
(assert (global (Mushroom world) (not (Parmense world))))
(assert (global (Mushroom world) (not (PolloAdAstra world))))
(assert (global (Mushroom world) (not (PrinceCarlo world))))
(assert (global (Mushroom world) (not (QuattroFormaggi world))))
(assert (global (Mushroom world) (not (Rosa world))))
(assert (global (Mushroom world) (not (Siciliana world))))
(assert (global (Mushroom world) (not (SloppyGiuseppe world))))
(assert (global (Mushroom world) (not (Soho world))))
(assert (global (Mushroom world) (not (UnclosedPizza world))))
(assert (global (Mushroom world) (not (Veneziana world))))
(assert (global (Napoletana world) (not (American world))))
(assert (global (Napoletana world) (not (AmericanHot world))))
(assert (global (Napoletana world) (not (Cajun world))))
(assert (global (Napoletana world) (not (Capricciosa world))))
(assert (global (Napoletana world) (not (Caprina world))))
(assert (global (Napoletana world) (not (Fiorentina world))))
(assert (global (Napoletana world) (not (FourSeasons world))))
(assert (global (Napoletana world) (not (FruttiDiMare world))))
(assert (global (Napoletana world) (not (Giardiniera world))))
(assert (global (Napoletana world) (not (LaReine world))))
(assert (global (Napoletana world) (not (Margherita world))))
(assert (global (Napoletana world) (not (Mushroom world))))
(assert (global (Napoletana world) (not (Parmense world))))
(assert (global (Napoletana world) (not (PolloAdAstra world))))
(assert (global (Napoletana world) (not (PrinceCarlo world))))
(assert (global (Napoletana world) (not (QuattroFormaggi world))))
(assert (global (Napoletana world) (not (Rosa world))))
(assert (global (Napoletana world) (not (Siciliana world))))
(assert (global (Napoletana world) (not (SloppyGiuseppe world))))
(assert (global (Napoletana world) (not (Soho world))))
(assert (global (Napoletana world) (not (UnclosedPizza world))))
(assert (global (Napoletana world) (not (Veneziana world))))
(assert (global (Parmense world) (not (American world))))
(assert (global (Parmense world) (not (AmericanHot world))))
(assert (global (Parmense world) (not (Cajun world))))
(assert (global (Parmense world) (not (Capricciosa world))))
(assert (global (Parmense world) (not (Caprina world))))
(assert (global (Parmense world) (not (Fiorentina world))))
(assert (global (Parmense world) (not (FourSeasons world))))
(assert (global (Parmense world) (not (FruttiDiMare world))))
(assert (global (Parmense world) (not (Giardiniera world))))
(assert (global (Parmense world) (not (LaReine world))))
(assert (global (Parmense world) (not (Margherita world))))
(assert (global (Parmense world) (not (Mushroom world))))
(assert (global (Parmense world) (not (Napoletana world))))
(assert (global (Parmense world) (not (PolloAdAstra world))))
(assert (global (Parmense world) (not (PrinceCarlo world))))
(assert (global (Parmense world) (not (QuattroFormaggi world))))
(assert (global (Parmense world) (not (Rosa world))))
(assert (global (Parmense world) (not (Siciliana world))))
(assert (global (Parmense world) (not (SloppyGiuseppe world))))
(assert (global (Parmense world) (not (Soho world))))
(assert (global (Parmense world) (not (UnclosedPizza world))))
(assert (global (Parmense world) (not (Veneziana world))))
(assert (global (PolloAdAstra world) (not (American world))))
(assert (global (PolloAdAstra world) (not (AmericanHot world))))
(assert (global (PolloAdAstra world) (not (Cajun world))))
(assert (global (PolloAdAstra world) (not (Capricciosa world))))
(assert (global (PolloAdAstra world) (not (Caprina world))))
(assert (global (PolloAdAstra world) (not (Fiorentina world))))
(assert (global (PolloAdAstra world) (not (FourSeasons world))))
(assert (global (PolloAdAstra world) (not (FruttiDiMare world))))
(assert (global (PolloAdAstra world) (not (Giardiniera world))))
(assert (global (PolloAdAstra world) (not (LaReine world))))
(assert (global (PolloAdAstra world) (not (Margherita world))))
(assert (global (PolloAdAstra world) (not (Mushroom world))))
(assert (global (PolloAdAstra world) (not (Napoletana world))))
(assert (global (PolloAdAstra world) (not (Parmense world))))
(assert (global (PolloAdAstra world) (not (PrinceCarlo world))))
(assert (global (PolloAdAstra world) (not (QuattroFormaggi world))))
(assert (global (PolloAdAstra world) (not (Rosa world))))
(assert (global (PolloAdAstra world) (not (Siciliana world))))
(assert (global (PolloAdAstra world) (not (SloppyGiuseppe world))))
(assert (global (PolloAdAstra world) (not (Soho world))))
(assert (global (PolloAdAstra world) (not (UnclosedPizza world))))
(assert (global (PolloAdAstra world) (not (Veneziana world))))
(assert (global (PrinceCarlo world) (not (American world))))
(assert (global (PrinceCarlo world) (not (AmericanHot world))))
(assert (global (PrinceCarlo world) (not (Cajun world))))
(assert (global (PrinceCarlo world) (not (Capricciosa world))))
(assert (global (PrinceCarlo world) (not (Caprina world))))
(assert (global (PrinceCarlo world) (not (Fiorentina world))))
(assert (global (PrinceCarlo world) (not (FourSeasons world))))
(assert (global (PrinceCarlo world) (not (FruttiDiMare world))))
(assert (global (PrinceCarlo world) (not (Giardiniera world))))
(assert (global (PrinceCarlo world) (not (LaReine world))))
(assert (global (PrinceCarlo world) (not (Margherita world))))
(assert (global (PrinceCarlo world) (not (Mushroom world))))
(assert (global (PrinceCarlo world) (not (Napoletana world))))
(assert (global (PrinceCarlo world) (not (Parmense world))))
(assert (global (PrinceCarlo world) (not (PolloAdAstra world))))
(assert (global (PrinceCarlo world) (not (QuattroFormaggi world))))
(assert (global (PrinceCarlo world) (not (Rosa world))))
(assert (global (PrinceCarlo world) (not (Siciliana world))))
(assert (global (PrinceCarlo world) (not (SloppyGiuseppe world))))
(assert (global (PrinceCarlo world) (not (Soho world))))
(assert (global (PrinceCarlo world) (not (UnclosedPizza world))))
(assert (global (PrinceCarlo world) (not (Veneziana world))))
(assert (global (QuattroFormaggi world) (not (American world))))
(assert (global (QuattroFormaggi world) (not (AmericanHot world))))
(assert (global (QuattroFormaggi world) (not (Cajun world))))
(assert (global (QuattroFormaggi world) (not (Capricciosa world))))
(assert (global (QuattroFormaggi world) (not (Caprina world))))
(assert (global (QuattroFormaggi world) (not (Fiorentina world))))
(assert (global (QuattroFormaggi world) (not (FourSeasons world))))
(assert (global (QuattroFormaggi world) (not (FruttiDiMare world))))
(assert (global (QuattroFormaggi world) (not (Giardiniera world))))
(assert (global (QuattroFormaggi world) (not (LaReine world))))
(assert (global (QuattroFormaggi world) (not (Margherita world))))
(assert (global (QuattroFormaggi world) (not (Mushroom world))))
(assert (global (QuattroFormaggi world) (not (Napoletana world))))
(assert (global (QuattroFormaggi world) (not (Parmense world))))
(assert (global (QuattroFormaggi world) (not (PolloAdAstra world))))
(assert (global (QuattroFormaggi world) (not (PrinceCarlo world))))
(assert (global (QuattroFormaggi world) (not (Rosa world))))
(assert (global (QuattroFormaggi world) (not (Siciliana world))))
(assert (global (QuattroFormaggi world) (not (SloppyGiuseppe world))))
(assert (global (QuattroFormaggi world) (not (Soho world))))
(assert (global (QuattroFormaggi world) (not (UnclosedPizza world))))
(assert (global (QuattroFormaggi world) (not (Veneziana world))))
(assert (global (Rosa world) (not (American world))))
(assert (global (Rosa world) (not (AmericanHot world))))
(assert (global (Rosa world) (not (Cajun world))))
(assert (global (Rosa world) (not (Capricciosa world))))
(assert (global (Rosa world) (not (Caprina world))))
(assert (global (Rosa world) (not (Fiorentina world))))
(assert (global (Rosa world) (not (FourSeasons world))))
(assert (global (Rosa world) (not (FruttiDiMare world))))
(assert (global (Rosa world) (not (Giardiniera world))))
(assert (global (Rosa world) (not (LaReine world))))
(assert (global (Rosa world) (not (Margherita world))))
(assert (global (Rosa world) (not (Mushroom world))))
(assert (global (Rosa world) (not (Napoletana world))))
(assert (global (Rosa world) (not (Parmense world))))
(assert (global (Rosa world) (not (PolloAdAstra world))))
(assert (global (Rosa world) (not (PrinceCarlo world))))
(assert (global (Rosa world) (not (QuattroFormaggi world))))
(assert (global (Rosa world) (not (Siciliana world))))
(assert (global (Rosa world) (not (SloppyGiuseppe world))))
(assert (global (Rosa world) (not (Soho world))))
(assert (global (Rosa world) (not (UnclosedPizza world))))
(assert (global (Rosa world) (not (Veneziana world))))
(assert (global (Siciliana world) (not (American world))))
(assert (global (Siciliana world) (not (AmericanHot world))))
(assert (global (Siciliana world) (not (Cajun world))))
(assert (global (Siciliana world) (not (Capricciosa world))))
(assert (global (Siciliana world) (not (Caprina world))))
(assert (global (Siciliana world) (not (Fiorentina world))))
(assert (global (Siciliana world) (not (FourSeasons world))))
(assert (global (Siciliana world) (not (FruttiDiMare world))))
(assert (global (Siciliana world) (not (Giardiniera world))))
(assert (global (Siciliana world) (not (LaReine world))))
(assert (global (Siciliana world) (not (Margherita world))))
(assert (global (Siciliana world) (not (Mushroom world))))
(assert (global (Siciliana world) (not (Napoletana world))))
(assert (global (Siciliana world) (not (Parmense world))))
(assert (global (Siciliana world) (not (PolloAdAstra world))))
(assert (global (Siciliana world) (not (PrinceCarlo world))))
(assert (global (Siciliana world) (not (QuattroFormaggi world))))
(assert (global (Siciliana world) (not (Rosa world))))
(assert (global (Siciliana world) (not (SloppyGiuseppe world))))
(assert (global (Siciliana world) (not (Soho world))))
(assert (global (Siciliana world) (not (UnclosedPizza world))))
(assert (global (Siciliana world) (not (Veneziana world))))
(assert (global (SloppyGiuseppe world) (not (American world))))
(assert (global (SloppyGiuseppe world) (not (AmericanHot world))))
(assert (global (SloppyGiuseppe world) (not (Cajun world))))
(assert (global (SloppyGiuseppe world) (not (Capricciosa world))))
(assert (global (SloppyGiuseppe world) (not (Caprina world))))
(assert (global (SloppyGiuseppe world) (not (Fiorentina world))))
(assert (global (SloppyGiuseppe world) (not (FourSeasons world))))
(assert (global (SloppyGiuseppe world) (not (FruttiDiMare world))))
(assert (global (SloppyGiuseppe world) (not (Giardiniera world))))
(assert (global (SloppyGiuseppe world) (not (LaReine world))))
(assert (global (SloppyGiuseppe world) (not (Margherita world))))
(assert (global (SloppyGiuseppe world) (not (Mushroom world))))
(assert (global (SloppyGiuseppe world) (not (Napoletana world))))
(assert (global (SloppyGiuseppe world) (not (Parmense world))))
(assert (global (SloppyGiuseppe world) (not (PolloAdAstra world))))
(assert (global (SloppyGiuseppe world) (not (PrinceCarlo world))))
(assert (global (SloppyGiuseppe world) (not (QuattroFormaggi world))))
(assert (global (SloppyGiuseppe world) (not (Rosa world))))
(assert (global (SloppyGiuseppe world) (not (Siciliana world))))
(assert (global (SloppyGiuseppe world) (not (Soho world))))
(assert (global (SloppyGiuseppe world) (not (UnclosedPizza world))))
(assert (global (SloppyGiuseppe world) (not (Veneziana world))))
(assert (global (Soho world) (not (American world))))
(assert (global (Soho world) (not (AmericanHot world))))
(assert (global (Soho world) (not (Cajun world))))
(assert (global (Soho world) (not (Capricciosa world))))
(assert (global (Soho world) (not (Caprina world))))
(assert (global (Soho world) (not (Fiorentina world))))
(assert (global (Soho world) (not (FourSeasons world))))
(assert (global (Soho world) (not (FruttiDiMare world))))
(assert (global (Soho world) (not (Giardiniera world))))
(assert (global (Soho world) (not (LaReine world))))
(assert (global (Soho world) (not (Margherita world))))
(assert (global (Soho world) (not (Mushroom world))))
(assert (global (Soho world) (not (Napoletana world))))
(assert (global (Soho world) (not (Parmense world))))
(assert (global (Soho world) (not (PolloAdAstra world))))
(assert (global (Soho world) (not (PrinceCarlo world))))
(assert (global (Soho world) (not (QuattroFormaggi world))))
(assert (global (Soho world) (not (Rosa world))))
(assert (global (Soho world) (not (Siciliana world))))
(assert (global (Soho world) (not (SloppyGiuseppe world))))
(assert (global (Soho world) (not (UnclosedPizza world))))
(assert (global (Soho world) (not (Veneziana world))))
(assert (global (UnclosedPizza world) (not (American world))))
(assert (global (UnclosedPizza world) (not (AmericanHot world))))
(assert (global (UnclosedPizza world) (not (Cajun world))))
(assert (global (UnclosedPizza world) (not (Capricciosa world))))
(assert (global (UnclosedPizza world) (not (Caprina world))))
(assert (global (UnclosedPizza world) (not (Fiorentina world))))
(assert (global (UnclosedPizza world) (not (FourSeasons world))))
(assert (global (UnclosedPizza world) (not (FruttiDiMare world))))
(assert (global (UnclosedPizza world) (not (Giardiniera world))))
(assert (global (UnclosedPizza world) (not (LaReine world))))
(assert (global (UnclosedPizza world) (not (Margherita world))))
(assert (global (UnclosedPizza world) (not (Mushroom world))))
(assert (global (UnclosedPizza world) (not (Napoletana world))))
(assert (global (UnclosedPizza world) (not (Parmense world))))
(assert (global (UnclosedPizza world) (not (PolloAdAstra world))))
(assert (global (UnclosedPizza world) (not (PrinceCarlo world))))
(assert (global (UnclosedPizza world) (not (QuattroFormaggi world))))
(assert (global (UnclosedPizza world) (not (Rosa world))))
(assert (global (UnclosedPizza world) (not (Siciliana world))))
(assert (global (UnclosedPizza world) (not (SloppyGiuseppe world))))
(assert (global (UnclosedPizza world) (not (Soho world))))
(assert (global (UnclosedPizza world) (not (Veneziana world))))
(assert (global (Veneziana world) (not (American world))))
(assert (global (Veneziana world) (not (AmericanHot world))))
(assert (global (Veneziana world) (not (Cajun world))))
(assert (global (Veneziana world) (not (Capricciosa world))))
(assert (global (Veneziana world) (not (Caprina world))))
(assert (global (Veneziana world) (not (Fiorentina world))))
(assert (global (Veneziana world) (not (FourSeasons world))))
(assert (global (Veneziana world) (not (FruttiDiMare world))))
(assert (global (Veneziana world) (not (Giardiniera world))))
(assert (global (Veneziana world) (not (LaReine world))))
(assert (global (Veneziana world) (not (Margherita world))))
(assert (global (Veneziana world) (not (Mushroom world))))
(assert (global (Veneziana world) (not (Napoletana world))))
(assert (global (Veneziana world) (not (Parmense world))))
(assert (global (Veneziana world) (not (PolloAdAstra world))))
(assert (global (Veneziana world) (not (PrinceCarlo world))))
(assert (global (Veneziana world) (not (QuattroFormaggi world))))
(assert (global (Veneziana world) (not (Rosa world))))
(assert (global (Veneziana world) (not (Siciliana world))))
(assert (global (Veneziana world) (not (SloppyGiuseppe world))))
(assert (global (Veneziana world) (not (Soho world))))
(assert (global (Veneziana world) (not (UnclosedPizza world))))
(assert (global (CajunSpiceTopping world) (not (RosemaryTopping world))))
(assert (global (RosemaryTopping world) (not (CajunSpiceTopping world))))
(assert (global (DeepPanBase world) (not (ThinAndCrispyBase world))))
(assert (global (ThinAndCrispyBase world) (not (DeepPanBase world))))
(assert (global (DomainConcept world) (not (ValuePartition world))))
(assert (global (ValuePartition world) (not (DomainConcept world))))
(assert (global (NonVegetarianPizza world) (not (VegetarianPizza world))))
(assert (global (VegetarianPizza world) (not (NonVegetarianPizza world))))
(assert (global (SlicedTomatoTopping world) (not (SundriedTomatoTopping world))))
(assert (global (SundriedTomatoTopping world) (not (SlicedTomatoTopping world))))

; class properties
(assert (global (Pizza world) (Food world)))
(assert (global (Pizza world) (dia hasBase (PizzaBase world)))))
(assert (global (PizzaBase world) (Food world)))
(assert (global (Food world) (DomainConcept world)))
(assert (global (Spiciness world) (ValuePartition world)))
(assert (global (Spiciness world) (or (Hot world) (Medium world) (Mild world))))
(assert (global (Hot world) (Spiciness world)))
(assert (global (Medium world) (Spiciness world)))
(assert (global (Mild world) (Spiciness world)))
(assert (global (PizzaTopping world) (Food world)))
(assert (global (American world) (NamedPizza world)))
(assert (global (American world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (American world) (dia hasTopping (PeperoniSausageTopping world)))))
(assert (global (American world) (dia hasTopping (TomatoTopping world)))))
(assert (global (American world) (box hasTopping (or (MozzarellaTopping world) (PeperoniSausageTopping world) (TomatoTopping world))))))
(assert (global (American world) (reachable hasCountryOfOrigin world America)))
(assert (global (NamedPizza world) (Pizza world)))
(assert (global (MozzarellaTopping world) (CheeseTopping world)))
(assert (global (MozzarellaTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (MozzarellaTopping world) (reachable hasCountryOfOrigin world Italy)))
(assert (global (PeperoniSausageTopping world) (MeatTopping world)))
(assert (global (PeperoniSausageTopping world) (dia hasSpiciness (Medium world)))))
(assert (global (TomatoTopping world) (VegetableTopping world)))
(assert (global (TomatoTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (AmericanHot world) (NamedPizza world)))
(assert (global (AmericanHot world) (dia hasTopping (HotGreenPepperTopping world)))))
(assert (global (AmericanHot world) (dia hasTopping (JalapenoPepperTopping world)))))
(assert (global (AmericanHot world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (AmericanHot world) (dia hasTopping (PeperoniSausageTopping world)))))
(assert (global (AmericanHot world) (dia hasTopping (TomatoTopping world)))))
(assert (global (AmericanHot world) (box hasTopping (or (HotGreenPepperTopping world) (JalapenoPepperTopping world) (MozzarellaTopping world) (PeperoniSausageTopping world) (TomatoTopping world))))))
(assert (global (AmericanHot world) (reachable hasCountryOfOrigin world America)))
(assert (global (HotGreenPepperTopping world) (GreenPepperTopping world)))
(assert (global (HotGreenPepperTopping world) (dia hasSpiciness (Hot world)))))
(assert (global (JalapenoPepperTopping world) (PepperTopping world)))
(assert (global (JalapenoPepperTopping world) (dia hasSpiciness (Hot world)))))
(assert (global (AnchoviesTopping world) (FishTopping world)))
(assert (global (FishTopping world) (PizzaTopping world)))
(assert (global (FishTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (ArtichokeTopping world) (VegetableTopping world)))
(assert (global (ArtichokeTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (VegetableTopping world) (PizzaTopping world)))
(assert (global (Mild world) (Spiciness world)))
(assert (global (AsparagusTopping world) (VegetableTopping world)))
(assert (global (AsparagusTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (Cajun world) (NamedPizza world)))
(assert (global (Cajun world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Cajun world) (dia hasTopping (OnionTopping world)))))
(assert (global (Cajun world) (dia hasTopping (PeperonataTopping world)))))
(assert (global (Cajun world) (dia hasTopping (PrawnsTopping world)))))
(assert (global (Cajun world) (dia hasTopping (TobascoPepperSauce world)))))
(assert (global (Cajun world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Cajun world) (box hasTopping (or (MozzarellaTopping world) (OnionTopping world) (PeperonataTopping world) (PrawnsTopping world) (TobascoPepperSauce world) (TomatoTopping world))))))
(assert (global (OnionTopping world) (VegetableTopping world)))
(assert (global (OnionTopping world) (dia hasSpiciness (Medium world)))))
(assert (global (PeperonataTopping world) (PepperTopping world)))
(assert (global (PeperonataTopping world) (dia hasSpiciness (Medium world)))))
(assert (global (PrawnsTopping world) (FishTopping world)))
(assert (global (TobascoPepperSauce world) (SauceTopping world)))
(assert (global (TobascoPepperSauce world) (dia hasSpiciness (Hot world)))))
(assert (global (CajunSpiceTopping world) (HerbSpiceTopping world)))
(assert (global (CajunSpiceTopping world) (dia hasSpiciness (Hot world)))))
(assert (global (HerbSpiceTopping world) (PizzaTopping world)))
(assert (global (Hot world) (Spiciness world)))
(assert (global (RosemaryTopping world) (HerbSpiceTopping world)))
(assert (global (RosemaryTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (CaperTopping world) (VegetableTopping world)))
(assert (global (CaperTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (Capricciosa world) (NamedPizza world)))
(assert (global (Capricciosa world) (dia hasTopping (AnchoviesTopping world)))))
(assert (global (Capricciosa world) (dia hasTopping (CaperTopping world)))))
(assert (global (Capricciosa world) (dia hasTopping (HamTopping world)))))
(assert (global (Capricciosa world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Capricciosa world) (dia hasTopping (OliveTopping world)))))
(assert (global (Capricciosa world) (dia hasTopping (PeperonataTopping world)))))
(assert (global (Capricciosa world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Capricciosa world) (box hasTopping (or (AnchoviesTopping world) (CaperTopping world) (HamTopping world) (MozzarellaTopping world) (OliveTopping world) (PeperonataTopping world) (TomatoTopping world))))))
(assert (global (HamTopping world) (MeatTopping world)))
(assert (global (OliveTopping world) (VegetableTopping world)))
(assert (global (OliveTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (Caprina world) (NamedPizza world)))
(assert (global (Caprina world) (dia hasTopping (GoatsCheeseTopping world)))))
(assert (global (Caprina world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Caprina world) (dia hasTopping (SundriedTomatoTopping world)))))
(assert (global (Caprina world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Caprina world) (box hasTopping (or (GoatsCheeseTopping world) (MozzarellaTopping world) (SundriedTomatoTopping world) (TomatoTopping world))))))
(assert (global (GoatsCheeseTopping world) (CheeseTopping world)))
(assert (global (GoatsCheeseTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (SundriedTomatoTopping world) (TomatoTopping world)))
(assert (global (SundriedTomatoTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (CheeseTopping world) (PizzaTopping world)))
(assert (global (CheeseyPizza world) (and (Pizza world) (dia hasTopping (CheeseTopping world))))))
(assert (global true (=> (and (Pizza world) (dia hasTopping (CheeseTopping world)))) (CheeseyPizza world))))
(assert (global (CheeseyVegetableTopping world) (CheeseTopping world)))
(assert (global (CheeseyVegetableTopping world) (VegetableTopping world)))
(assert (global (ChickenTopping world) (MeatTopping world)))
(assert (global (ChickenTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (MeatTopping world) (PizzaTopping world)))
(assert (global (Country world) (and (DomainConcept world) (or (= world pizza.America) (= world pizza.England) (= world pizza.France) (= world pizza.Germany) (= world pizza.Italy)))))
(assert (global true (=> (and (DomainConcept world) (or (= world pizza.America) (= world pizza.England) (= world pizza.France) (= world pizza.Germany) (= world pizza.Italy))) (Country world))))
(assert (global (DeepPanBase world) (PizzaBase world)))
(assert (global (ThinAndCrispyBase world) (PizzaBase world)))
(assert (global (Fiorentina world) (NamedPizza world)))
(assert (global (Fiorentina world) (dia hasTopping (GarlicTopping world)))))
(assert (global (Fiorentina world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Fiorentina world) (dia hasTopping (OliveTopping world)))))
(assert (global (Fiorentina world) (dia hasTopping (ParmesanTopping world)))))
(assert (global (Fiorentina world) (dia hasTopping (SpinachTopping world)))))
(assert (global (Fiorentina world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Fiorentina world) (box hasTopping (or (GarlicTopping world) (MozzarellaTopping world) (OliveTopping world) (ParmesanTopping world) (SpinachTopping world) (TomatoTopping world))))))
(assert (global (GarlicTopping world) (VegetableTopping world)))
(assert (global (GarlicTopping world) (dia hasSpiciness (Medium world)))))
(assert (global (ParmesanTopping world) (CheeseTopping world)))
(assert (global (ParmesanTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (SpinachTopping world) (VegetableTopping world)))
(assert (global (SpinachTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (FourCheesesTopping world) (CheeseTopping world)))
(assert (global (FourCheesesTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (FourSeasons world) (NamedPizza world)))
(assert (global (FourSeasons world) (dia hasTopping (AnchoviesTopping world)))))
(assert (global (FourSeasons world) (dia hasTopping (CaperTopping world)))))
(assert (global (FourSeasons world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (FourSeasons world) (dia hasTopping (MushroomTopping world)))))
(assert (global (FourSeasons world) (dia hasTopping (OliveTopping world)))))
(assert (global (FourSeasons world) (dia hasTopping (PeperoniSausageTopping world)))))
(assert (global (FourSeasons world) (dia hasTopping (TomatoTopping world)))))
(assert (global (FourSeasons world) (box hasTopping (or (AnchoviesTopping world) (CaperTopping world) (MozzarellaTopping world) (MushroomTopping world) (OliveTopping world) (PeperoniSausageTopping world) (TomatoTopping world))))))
(assert (global (MushroomTopping world) (VegetableTopping world)))
(assert (global (MushroomTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (FruitTopping world) (PizzaTopping world)))
(assert (global (FruttiDiMare world) (NamedPizza world)))
(assert (global (FruttiDiMare world) (dia hasTopping (GarlicTopping world)))))
(assert (global (FruttiDiMare world) (dia hasTopping (MixedSeafoodTopping world)))))
(assert (global (FruttiDiMare world) (dia hasTopping (TomatoTopping world)))))
(assert (global (FruttiDiMare world) (box hasTopping (or (GarlicTopping world) (MixedSeafoodTopping world) (TomatoTopping world))))))
(assert (global (MixedSeafoodTopping world) (FishTopping world)))
(assert (global (Medium world) (Spiciness world)))
(assert (global (Giardiniera world) (NamedPizza world)))
(assert (global (Giardiniera world) (dia hasTopping (LeekTopping world)))))
(assert (global (Giardiniera world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Giardiniera world) (dia hasTopping (MushroomTopping world)))))
(assert (global (Giardiniera world) (dia hasTopping (OliveTopping world)))))
(assert (global (Giardiniera world) (dia hasTopping (PeperonataTopping world)))))
(assert (global (Giardiniera world) (dia hasTopping (PetitPoisTopping world)))))
(assert (global (Giardiniera world) (dia hasTopping (SlicedTomatoTopping world)))))
(assert (global (Giardiniera world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Giardiniera world) (box hasTopping (or (LeekTopping world) (MozzarellaTopping world) (MushroomTopping world) (OliveTopping world) (PeperonataTopping world) (PetitPoisTopping world) (SlicedTomatoTopping world) (TomatoTopping world))))))
(assert (global (LeekTopping world) (VegetableTopping world)))
(assert (global (LeekTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (PetitPoisTopping world) (VegetableTopping world)))
(assert (global (PetitPoisTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (SlicedTomatoTopping world) (TomatoTopping world)))
(assert (global (SlicedTomatoTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (GorgonzolaTopping world) (CheeseTopping world)))
(assert (global (GorgonzolaTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (GreenPepperTopping world) (PepperTopping world)))
(assert (global (PepperTopping world) (VegetableTopping world)))
(assert (global (HotSpicedBeefTopping world) (MeatTopping world)))
(assert (global (HotSpicedBeefTopping world) (dia hasSpiciness (Hot world)))))
(assert (global (IceCream world) (Food world)))
(assert (global (IceCream world) (dia hasTopping (FruitTopping world)))))
(assert (global (InterestingPizza world) (and (Pizza world) true)))
(assert (global true (=> (and (Pizza world) true) (InterestingPizza world))))
(assert (global (LaReine world) (NamedPizza world)))
(assert (global (LaReine world) (dia hasTopping (HamTopping world)))))
(assert (global (LaReine world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (LaReine world) (dia hasTopping (MushroomTopping world)))))
(assert (global (LaReine world) (dia hasTopping (OliveTopping world)))))
(assert (global (LaReine world) (dia hasTopping (TomatoTopping world)))))
(assert (global (LaReine world) (box hasTopping (or (HamTopping world) (MozzarellaTopping world) (MushroomTopping world) (OliveTopping world) (TomatoTopping world))))))
(assert (global (Margherita world) (NamedPizza world)))
(assert (global (Margherita world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Margherita world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Margherita world) (box hasTopping (or (MozzarellaTopping world) (TomatoTopping world))))))
(assert (global (MeatyPizza world) (and (Pizza world) (dia hasTopping (MeatTopping world))))))
(assert (global true (=> (and (Pizza world) (dia hasTopping (MeatTopping world)))) (MeatyPizza world))))
(assert (global (Mushroom world) (NamedPizza world)))
(assert (global (Mushroom world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Mushroom world) (dia hasTopping (MushroomTopping world)))))
(assert (global (Mushroom world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Mushroom world) (box hasTopping (or (MozzarellaTopping world) (MushroomTopping world) (TomatoTopping world))))))
(assert (global (Napoletana world) (NamedPizza world)))
(assert (global (Napoletana world) (dia hasTopping (AnchoviesTopping world)))))
(assert (global (Napoletana world) (dia hasTopping (CaperTopping world)))))
(assert (global (Napoletana world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Napoletana world) (dia hasTopping (OliveTopping world)))))
(assert (global (Napoletana world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Napoletana world) (box hasTopping (or (AnchoviesTopping world) (CaperTopping world) (MozzarellaTopping world) (OliveTopping world) (TomatoTopping world))))))
(assert (global (Napoletana world) (reachable hasCountryOfOrigin world Italy)))
(assert (global (NonVegetarianPizza world) (and (Pizza world) (not (VegetarianPizza world)))))
(assert (global true (=> (and (Pizza world) (not (VegetarianPizza world))) (NonVegetarianPizza world))))
(assert (global (VegetarianPizza world) (and (Pizza world) (not (dia hasTopping (FishTopping world)))) (not (dia hasTopping (MeatTopping world)))))))
(assert (global true (=> (and (Pizza world) (not (dia hasTopping (FishTopping world)))) (not (dia hasTopping (MeatTopping world))))) (VegetarianPizza world))))
(assert (global (NutTopping world) (PizzaTopping world)))
(assert (global (NutTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (ParmaHamTopping world) (HamTopping world)))
(assert (global (ParmaHamTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (Parmense world) (NamedPizza world)))
(assert (global (Parmense world) (dia hasTopping (AsparagusTopping world)))))
(assert (global (Parmense world) (dia hasTopping (HamTopping world)))))
(assert (global (Parmense world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Parmense world) (dia hasTopping (ParmesanTopping world)))))
(assert (global (Parmense world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Parmense world) (box hasTopping (or (AsparagusTopping world) (HamTopping world) (MozzarellaTopping world) (ParmesanTopping world) (TomatoTopping world))))))
(assert (global (PineKernels world) (NutTopping world)))
(assert (global (PolloAdAstra world) (NamedPizza world)))
(assert (global (PolloAdAstra world) (dia hasTopping (CajunSpiceTopping world)))))
(assert (global (PolloAdAstra world) (dia hasTopping (ChickenTopping world)))))
(assert (global (PolloAdAstra world) (dia hasTopping (GarlicTopping world)))))
(assert (global (PolloAdAstra world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (PolloAdAstra world) (dia hasTopping (RedOnionTopping world)))))
(assert (global (PolloAdAstra world) (dia hasTopping (SweetPepperTopping world)))))
(assert (global (PolloAdAstra world) (dia hasTopping (TomatoTopping world)))))
(assert (global (PolloAdAstra world) (box hasTopping (or (CajunSpiceTopping world) (ChickenTopping world) (GarlicTopping world) (MozzarellaTopping world) (RedOnionTopping world) (SweetPepperTopping world) (TomatoTopping world))))))
(assert (global (RedOnionTopping world) (OnionTopping world)))
(assert (global (SweetPepperTopping world) (PepperTopping world)))
(assert (global (SweetPepperTopping world) (dia hasSpiciness (Mild world)))))
(assert (global (PrinceCarlo world) (NamedPizza world)))
(assert (global (PrinceCarlo world) (dia hasTopping (LeekTopping world)))))
(assert (global (PrinceCarlo world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (PrinceCarlo world) (dia hasTopping (ParmesanTopping world)))))
(assert (global (PrinceCarlo world) (dia hasTopping (RosemaryTopping world)))))
(assert (global (PrinceCarlo world) (dia hasTopping (TomatoTopping world)))))
(assert (global (PrinceCarlo world) (box hasTopping (or (LeekTopping world) (MozzarellaTopping world) (ParmesanTopping world) (RosemaryTopping world) (TomatoTopping world))))))
(assert (global (QuattroFormaggi world) (NamedPizza world)))
(assert (global (QuattroFormaggi world) (dia hasTopping (FourCheesesTopping world)))))
(assert (global (QuattroFormaggi world) (dia hasTopping (TomatoTopping world)))))
(assert (global (QuattroFormaggi world) (box hasTopping (or (FourCheesesTopping world) (TomatoTopping world))))))
(assert (global (RealItalianPizza world) (box hasBase (ThinAndCrispyBase world)))))
(assert (global (RealItalianPizza world) (and (Pizza world) (reachable hasCountryOfOrigin world Italy))))
(assert (global true (=> (and (Pizza world) (reachable hasCountryOfOrigin world Italy)) (RealItalianPizza world))))
(assert (global (RocketTopping world) (VegetableTopping world)))
(assert (global (RocketTopping world) (dia hasSpiciness (Medium world)))))
(assert (global (Rosa world) (NamedPizza world)))
(assert (global (Rosa world) (dia hasTopping (GorgonzolaTopping world)))))
(assert (global (Rosa world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Rosa world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Rosa world) (box hasTopping (or (GorgonzolaTopping world) (MozzarellaTopping world) (TomatoTopping world))))))
(assert (global (SauceTopping world) (PizzaTopping world)))
(assert (global (Siciliana world) (NamedPizza world)))
(assert (global (Siciliana world) (dia hasTopping (AnchoviesTopping world)))))
(assert (global (Siciliana world) (dia hasTopping (ArtichokeTopping world)))))
(assert (global (Siciliana world) (dia hasTopping (GarlicTopping world)))))
(assert (global (Siciliana world) (dia hasTopping (HamTopping world)))))
(assert (global (Siciliana world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Siciliana world) (dia hasTopping (OliveTopping world)))))
(assert (global (Siciliana world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Siciliana world) (box hasTopping (or (AnchoviesTopping world) (ArtichokeTopping world) (GarlicTopping world) (HamTopping world) (MozzarellaTopping world) (OliveTopping world) (TomatoTopping world))))))
(assert (global (SloppyGiuseppe world) (NamedPizza world)))
(assert (global (SloppyGiuseppe world) (dia hasTopping (GreenPepperTopping world)))))
(assert (global (SloppyGiuseppe world) (dia hasTopping (HotSpicedBeefTopping world)))))
(assert (global (SloppyGiuseppe world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (SloppyGiuseppe world) (dia hasTopping (OnionTopping world)))))
(assert (global (SloppyGiuseppe world) (dia hasTopping (TomatoTopping world)))))
(assert (global (SloppyGiuseppe world) (box hasTopping (or (GreenPepperTopping world) (HotSpicedBeefTopping world) (MozzarellaTopping world) (OnionTopping world) (TomatoTopping world))))))
(assert (global (Soho world) (NamedPizza world)))
(assert (global (Soho world) (dia hasTopping (GarlicTopping world)))))
(assert (global (Soho world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Soho world) (dia hasTopping (OliveTopping world)))))
(assert (global (Soho world) (dia hasTopping (ParmesanTopping world)))))
(assert (global (Soho world) (dia hasTopping (RocketTopping world)))))
(assert (global (Soho world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Soho world) (box hasTopping (or (GarlicTopping world) (MozzarellaTopping world) (OliveTopping world) (ParmesanTopping world) (RocketTopping world) (TomatoTopping world))))))
(assert (global (SpicyPizza world) (and (Pizza world) (dia hasTopping (SpicyTopping world))))))
(assert (global true (=> (and (Pizza world) (dia hasTopping (SpicyTopping world)))) (SpicyPizza world))))
(assert (global (SpicyTopping world) (and (PizzaTopping world) (dia hasSpiciness (Hot world))))))
(assert (global true (=> (and (PizzaTopping world) (dia hasSpiciness (Hot world)))) (SpicyTopping world))))
(assert (global (SpicyPizzaEquivalent world) (and (Pizza world) (dia hasTopping (and (PizzaTopping world) (dia hasSpiciness (Hot world)))))))))
(assert (global true (=> (and (Pizza world) (dia hasTopping (and (PizzaTopping world) (dia hasSpiciness (Hot world))))))) (SpicyPizzaEquivalent world))))
(assert (global (SultanaTopping world) (FruitTopping world)))
(assert (global (SultanaTopping world) (dia hasSpiciness (Medium world)))))
(assert (global (ThinAndCrispyPizza world) (and (Pizza world) (box hasBase (ThinAndCrispyBase world))))))
(assert (global true (=> (and (Pizza world) (box hasBase (ThinAndCrispyBase world)))) (ThinAndCrispyPizza world))))
(assert (global (UnclosedPizza world) (Pizza world)))
(assert (global (UnclosedPizza world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (VegetarianPizzaEquivalent1 world) (and (Pizza world) (box hasTopping (VegetarianTopping world))))))
(assert (global true (=> (and (Pizza world) (box hasTopping (VegetarianTopping world)))) (VegetarianPizzaEquivalent1 world))))
(assert (global (VegetarianTopping world) (and (PizzaTopping world) (or (CheeseTopping world) (FruitTopping world) (HerbSpiceTopping world) (NutTopping world) (SauceTopping world) (VegetableTopping world)))))
(assert (global true (=> (and (PizzaTopping world) (or (CheeseTopping world) (FruitTopping world) (HerbSpiceTopping world) (NutTopping world) (SauceTopping world) (VegetableTopping world))) (VegetarianTopping world))))
(assert (global (VegetarianPizzaEquivalent2 world) (and (Pizza world) (box hasTopping (or (CheeseTopping world) (FruitTopping world) (HerbSpiceTopping world) (NutTopping world) (SauceTopping world) (VegetableTopping world)))))))
(assert (global true (=> (and (Pizza world) (box hasTopping (or (CheeseTopping world) (FruitTopping world) (HerbSpiceTopping world) (NutTopping world) (SauceTopping world) (VegetableTopping world))))) (VegetarianPizzaEquivalent2 world))))
(assert (global (Veneziana world) (NamedPizza world)))
(assert (global (Veneziana world) (dia hasTopping (CaperTopping world)))))
(assert (global (Veneziana world) (dia hasTopping (MozzarellaTopping world)))))
(assert (global (Veneziana world) (dia hasTopping (OliveTopping world)))))
(assert (global (Veneziana world) (dia hasTopping (OnionTopping world)))))
(assert (global (Veneziana world) (dia hasTopping (PineKernels world)))))
(assert (global (Veneziana world) (dia hasTopping (SultanaTopping world)))))
(assert (global (Veneziana world) (dia hasTopping (TomatoTopping world)))))
(assert (global (Veneziana world) (box hasTopping (or (CaperTopping world) (MozzarellaTopping world) (OliveTopping world) (OnionTopping world) (PineKernels world) (SultanaTopping world) (TomatoTopping world))))))
(assert (global (Veneziana world) (reachable hasCountryOfOrigin world Italy)))